export const ActionTypes = {
  SHOW_DETAILS: "SHOW_DETAILS",
  CITY_DETAILS: "CITY_DETAILS",
  SEARCH_FILTER: "SEARCH_FILTER",
  SHOW_DETAILS_FLIGHT:"SHOW_DETAILS_FLIGHT",
  SHOW_DETAILS_TRAIN:"SHOW_DETAILS_TRAIN"
};
